/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import controller.AppointmentController;

/**
 *
 * @author Tenuri
 */
public class Appointment extends javax.swing.JFrame {

    /**
     * Creates new form Appointment
     */
    public Appointment() {
        initComponents();
        setLocationRelativeTo(null);
        System.out.println("Appointment from constructor called");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpatient = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        btnnum = new javax.swing.JButton();
        btnconfirm = new javax.swing.JButton();
        cmbdoc = new javax.swing.JComboBox<>();
        Jdate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        Btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Life Bloom (11).png"))); // NOI18N
        Back.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 490));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Appointment");
        Back.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 230, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Patient Name");
        Back.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Age");
        Back.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Doctor");
        Back.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Number");
        Back.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        txtpatient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Back.add(txtpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 220, -1));

        txtage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Back.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 220, -1));

        txtnum.setEditable(false);
        txtnum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Back.add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 220, -1));

        btnnum.setBackground(new java.awt.Color(204, 255, 204));
        btnnum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnum.setText("Available number");
        btnnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumActionPerformed(evt);
            }
        });
        Back.add(btnnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, 40));

        btnconfirm.setBackground(new java.awt.Color(204, 255, 204));
        btnconfirm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnconfirm.setText("Confirm");
        Back.add(btnconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        cmbdoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbdoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr Ann De Silva", "Dr Jessica Swetha", "Dr Lewis Tomlinson", "Dr Glenn fernando", "Dr David Perera", " " }));
        Back.add(cmbdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 220, -1));

        Jdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Back.add(Jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 220, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Date");
        Back.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        Btnback.setBackground(new java.awt.Color(204, 204, 255));
        Btnback.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Btnback.setText("Back");
        Btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbackActionPerformed(evt);
            }
        });
        Back.add(Btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnumActionPerformed

    private void BtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Appointment appointmentView = new Appointment();
                new AppointmentController(appointmentView); 
                appointmentView.setVisible(true);
            }
        });
    }

    // Button to check available appointment number
public JButton getCheckButton() {
    return btnnum; 
}

// Button to confirm appointment
public JButton getConfirmButton() {
    return btnconfirm;
}

// Field for patient's name
public JTextField getPatientNameField() {
    return txtpatient;
}

// Field for age
public JTextField getAgeField() {
    return txtage;
}

// Combo box for doctor
public JComboBox<String> getDoctorComboBox() {
    return cmbdoc;
}

// Appointment number field 
public JTextField getAppointmentNumberField() {
    return txtnum;
}

public com.toedter.calendar.JDateChooser getDateChooser() {
    return Jdate;
}
public JButton getBackButton() {
    return Btnback;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Back;
    private javax.swing.JButton Btnback;
    private com.toedter.calendar.JDateChooser Jdate;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JButton btnnum;
    private javax.swing.JComboBox<String> cmbdoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtpatient;
    // End of variables declaration//GEN-END:variables
}
